#!/usr/bin/python

import pdb
import sys
import traceback
from xml.dom import expatbuilder
import click
import dbus
import dbus.glib
import gobject

# Simple app using Tomboy dbus api
# see: https://arstechnica.com/information-technology/2007/09/using-the-tomboy-d-bus-interface/


class Note(object):

    def __init__(self, uri, interface=None):
        self.uri = uri
        self.interface = interface or get_interface()

    def __str__(self):
        return 'Note(%r)' % self.uri

    @property
    def tags(self):
        return self.interface.GetTagsForNote(self.uri) or []

    @property
    def title(self):
        return self.interface.GetNoteTitle(self.uri)

    @property
    def contents(self):
        return self.interface.GetNoteContents(self.uri)

    @property
    def contents_xml(self):
        return self.interface.GetNoteContentsXml(self.uri)

    @property
    def xml(self):
        return self.interface.GetNoteCompleteXml(self.uri)

    def add_tag(self, tag):
        return self.interface.AddTagToNote(self.uri, str(tag))

    def display(self, search=False):
        if search:
            return self.interface.DisplayNoteWithSearch(self.uri)
        else:
            return self.interface.DisplayNote(self.uri)

    def hide(self):
        return self.interface.HideNote(self.uri)

    @property
    def create_date(self):
        return self.interface.GetNoteCreateDate(self.uri)

    @property
    def change_date(self):
        return self.interface.GetNoteChangeDate(self.uri)


class NoteParamType(click.ParamType):
    name = 'note'

    def convert(self, value, param, ctx):
        # TODO: avoid tomboy global
        uri = tomboy.FindNote(value)
        if not uri:
            self.fail('No such note: %s' % value, param, ctx)
        return Note(uri)

NOTE = NoteParamType()


@click.group()
def tb():
    # main command
    pass


@tb.command('list')
@click.option('-t', '--tag', help='list notes with tag')
@click.option('-b/', '--notebook', help='list notes in notebook')
@click.option('--show-tags/--no-show-tags', help='show tags')
def list(tag, notebook, show_tags):
    """List notes"""
    if notebook:
        tag = "system:notebook:%s" % notebook
    if tag:
        notes = tomboy.GetAllNotesWithTag(tag)
    else:
        notes = tomboy.ListAllNotes()
    notes = [Note(uri) for uri in notes]
    for note in sorted(notes, key = lambda n: n.change_date):
        print note.title
        if show_tags:
            for t in note.tags:
                print "    - %s" % t


@tb.command('start')
def start():
    """Display the Start Here note"""
    tomboy.DisplayNote(tomboy.FindStartHereNote())


@tb.command('show')
@click.argument('note', type=NOTE)
@click.option('--xml/--no-xml', help='show complete xml')
@click.option('--xc/', '--xml-contents/--no-xml-contents',
              help='show xml contents')
def show(note, xml, xml_contents):
    """Output the contents of the note"""
    if xml:
        print note.xml
    elif xml_contents:
        print note.contents_xml
    else:
        print note.contents


@tb.command('tag')
@click.option('-b/', '--notebook/--no-notebook', help='add notebook tag')
@click.argument('note', type=NOTE)
@click.argument('tag')
def tag(notebook, note, tag):
    """Add a tag to a note"""
    if notebook:
        tag = "system:notebook:archive:%s"
    note.add_tag(tag)


@tb.command()
def watch():
    """Watch Tomboy activity"""
    bus = dbus.SessionBus()

    def onNoteAdded(uri):
        print "Note created: %s" % uri
    bus.add_signal_receiver(
            onNoteAdded,
            dbus_interface="org.gnome.Tomboy.RemoteControl",
            signal_name="NoteAdded")

    def onNoteSaved(uri):
        print "Note %s saved!" % tomboy.GetNoteTitle(uri)
    bus.add_signal_receiver(
            onNoteSaved,
            dbus_interface="org.gnome.Tomboy.RemoteControl",
            signal_name="NoteSaved")

    def onNoteDeleted(uri, title):
        print "Note %s deleted! (was %s)" % (title, uri)
    bus.add_signal_receiver(
            onNoteDeleted,
            dbus_interface="org.gnome.Tomboy.RemoteControl",
            signal_name="NoteDeleted")

    # Loop until manually terminated
    gobject.MainLoop().run()


def get_interface():
    # Get the D-Bus session bus
    bus = dbus.SessionBus()
    # Access the Tomboy D-Bus object
    obj = bus.get_object(
            "org.gnome.Tomboy",
            "/org/gnome/Tomboy/RemoteControl")
    # Access the Tomboy remote control interface
    tomboy = dbus.Interface(obj, "org.gnome.Tomboy.RemoteControl")
    return tomboy


@tb.command('mknote')
@click.argument('title', nargs=-1)
@click.option('--show/--no-show', '-s/')
@click.option('--xml/--no-xml', '-x/')
@click.option('-f', '--file', '--filename')
@click.option('--test/--no-test', '-n/')
def mknote(title, show, xml, filename, test):
    """Create a note from stdin or file"""

    # read our content
    if filename:
        with open(filename, 'r') as fp:
            contents = fp.read()
    else:
        contents = sys.stdin.read()

    # and validate it
    if xml:
        document = expatbuilder.parseString(contents, False)
        top = document.getElementsByTagName('note-content')[0]
        # TODO - combine with similar code in dup command
        node = top.firstChild
        if node.nodeType != node.TEXT_NODE:
            # Could happen if title has formatting
            raise ValueError('Unable to find title')
        parts = node.data.split('\n\n', 1)
        if len(parts) < 2:
            raise ValueError('Unable to find title')

    # sort out our title
    if title:
        title = ' '.join(title)
        if test:
            new_note = 'TEST'
        else:
            new_note = tomboy.CreateNamedNote(title)
    else:
        if test:
            title = 'UNKNOWN'
            new_note = 'TEST'
        else:
            new_note = tomboy.CreateNote()
            title = tomboy.GetNoteTitle(new_note)
    print('New note: %s' % title)

    if not new_note:
        print('Unable to create note: %s' % title)
        return 1

    if not test:
        tomboy.AddTagToNote(new_note, "commandline")

    if xml:
        # replace the title in contents
        node.data = title + '\n\n' + parts[1]
        contents = top.toxml()
        if test:
            print(contents)
            return
        tomboy.SetNoteContentsXml(new_note, contents)
        if show:
            tomboy.DisplayNote(new_note)
    elif test:
        return
    else:
        contents = tomboy.GetNoteTitle(new_note) + "\n\n" + contents
        # [!] Workaround for a bug in Tomboy
        #     We must display the note before updating contents
        #     see: https://osmanov-dev-notes.blogspot.com/2010/10/importing-text-files-into-tomboy.html
        tomboy.DisplayNote(new_note)
        tomboy.SetNoteContents(new_note, contents)
        if not show:
            tomboy.HideNote(new_note)


@tb.command('dup')
@click.argument('note', type=NOTE)
@click.option('--new-title', '-t', help='title for the new note')
@click.option('--show/--no-show', '-s/')
def dup(note, new_title, show):
    """Duplicate a note"""
    src = note
    if not new_title:
        new_title = "Copy of %s" % src.title
    chk = tomboy.FindNote(new_title)
    if chk:
        print('Already exists: %s' % new_title)
        return 1
    contents = src.contents_xml
    if not contents:
        # should not happen
        print('No contents for note: %s' % src)
        return 1
    # change title in contents
    document = expatbuilder.parseString(contents, False)
    top = document.getElementsByTagName('note-content')[0]
    # [!] TomBoy has a questionable design here with the literal html-ish
    #     content included directly in the node. This content uses literal
    #     whitespace and expects the first line to be match the title.
    #     That is why we have the following assertions
    node = top.firstChild
    if node.nodeType != node.TEXT_NODE:
        # Could happen if title has formatting
        raise ValueError('Unable to find title')
    parts = node.data.split('\n\n', 1)
    if len(parts) < 2:
        raise ValueError('Unable to find title')
    # ok, replace the title
    node.data = new_title + '\n\n' + parts[1]
    contents = top.toxml()
    new_note = tomboy.CreateNamedNote(new_title)
    tomboy.AddTagToNote(new_note, "duplicate")
    tomboy.SetNoteContentsXml(new_note, contents)
    if show:
        tomboy.DisplayNote(new_note)


if __name__ == '__main__':
    try:
        # TODO: avoid tomboy global
        tomboy = get_interface()
        tb()
    except Exception:
        etype, e, tb = sys.exc_info()
        traceback.print_exc()
        pdb.post_mortem(tb)
